config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path("", include("news_app.urls")),
    path("account/", include("accounts.urls")),
] + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path("", include("news_app.urls")),
    path("account/", include("accounts.urls")),
)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news_app/models.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models
from django.urls import reverse


# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=News.Status.Published)


class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class News(models.Model):
    class Status(models.TextChoices):
        Draft = "DF", "Draft"
        Published = "PB", "Published"

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    body = models.TextField()
    image = models.ImageField(upload_to='news/images')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    publish_time = models.DateTimeField(default=timezone.now)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.Draft)
    objects = models.Manager()  # default manager
    published = PublishedManager()

    class Meta:
        ordering = ["-publish_time"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("news_detail_page", args=[self.slug])


class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=150)
    message = models.TextField()


    def __str__(self):
        return self.email


class Comment(models.Model):
    news = models.ForeignKey(News, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    body = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created_time"]

    def __str__(self):
        return f"Comment - {self.body} by {self.user}"

templates/crud/news_cread.html
{% extends 'news/base.html' %}
{% load static %}

{% block title %}Yangilikni qo'shish{% endblock title %}

{% block content %}
    <h2 class="text-center">Yangilik qo'shish</h2>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-group-justified ml-3" style="color: #46b8da">Yangilikni qo'shish...</button>
    </form>
    
    
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    <script>
        $(document).ready(function(){
            $('#id_title').on('input', function(){
                var title = $(this).val();
                var slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-');
                $('#id_slug').val(slug);
            });
        });
    </script>
    
{% endblock %}

templates/crud/news_delete.html
{% extends 'news/base.html' %}
{% load static %}

{% block title %}{{ news.title }}{% endblock title %}

{% block content %}
    <h2 class="text-center">Joriy yangilikni ochirish</h2>
    <form method="post">{% csrf_token %}
        <p>{{ news.title|truncatewords:3 }}... sarvlahali yangilikni o'chirmoqchimisiz?</p>
        <button type="submit" class="btn btn-danger ml-2">Tastiqlayman.</button>
    </form>
{% endblock %}

templates/crud/news_edit.html
{% extends 'news/base.html' %}
{% load static %}

{% block title %}{{ news.title }}{% endblock title %}

{% block content %}
    <h2 class="text-center">Joriy yangilikni tahrirlash</h2>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-green ml-2">Tahrirlash...</button>
    </form>
{% endblock %}